package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	graphql_model1 "pulse/graph/graphql_model"

	"github.com/google/uuid"
)

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, userID uuid.UUID, roleName string) (*graphql_model1.User, error) {
	panic(fmt.Errorf("not implemented: AssignRole - assignRole"))
}

// RemoveRole is the resolver for the removeRole field.
func (r *mutationResolver) RemoveRole(ctx context.Context, userID uuid.UUID, roleName string) (*graphql_model1.User, error) {
	panic(fmt.Errorf("not implemented: RemoveRole - removeRole"))
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*graphql_model1.Role, error) {
	panic(fmt.Errorf("not implemented: Roles - roles"))
}
