package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	graphql_model1 "pulse/graph/graphql_model"
	"time"

	"github.com/google/uuid"
)

// Tokens is the resolver for the tokens field.
func (r *queryResolver) Tokens(ctx context.Context) ([]*graphql_model1.Token, error) {
	panic(fmt.Errorf("not implemented: Tokens - tokens"))
}

// Token is the resolver for the token field.
func (r *queryResolver) Token(ctx context.Context, id uuid.UUID) (*graphql_model1.Token, error) {
	panic(fmt.Errorf("not implemented: Token - token"))
}

// TokenPriceHistory is the resolver for the tokenPriceHistory field.
func (r *queryResolver) TokenPriceHistory(ctx context.Context, id uuid.UUID, from time.Time, to time.Time) ([]*graphql_model1.HistoricalPrice, error) {
	panic(fmt.Errorf("not implemented: TokenPriceHistory - tokenPriceHistory"))
}
