package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	"pulse/graph/generated"
	"pulse/graph/graphql_model"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*graphql_model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
