package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	"pulse/graph/graphql_model"
	"pulse/internal/auth"

	"github.com/google/uuid"
)

// CreateWallet is the resolver for the createWallet field.
func (r *mutationResolver) CreateWallet(ctx context.Context, input graphql_model.CreateWalletInput) (*graphql_model.Wallet, error) {
	userId := auth.UserFromContext(ctx)
	fmt.Printf(" resolver user: %s", userId)
	return r.WalletService.CreateWallet(ctx, &input)
}

// CreateSubwallet is the resolver for the createSubwallet field.
func (r *mutationResolver) CreateSubwallet(ctx context.Context, input graphql_model.CreateSubwalletInput) (*graphql_model.Subwallet, error) {
	return r.WalletService.CreateSubwallet(ctx, &input)
}

// Wallets is the resolver for the wallets field.
func (r *queryResolver) Wallets(ctx context.Context) ([]*graphql_model.Wallet, error) {
	return r.WalletService.GetWallets(ctx)
}

// Wallet is the resolver for the wallet field.
func (r *queryResolver) Wallet(ctx context.Context, id uuid.UUID) (*graphql_model.Wallet, error) {
	// return r.WalletService.GetWallet(ctx, id)
	return nil, nil
}

// Subwallet is the resolver for the subwallet field.
func (r *queryResolver) Subwallet(ctx context.Context, id uuid.UUID) (*graphql_model.Subwallet, error) {
	return r.WalletService.GetSubwallet(ctx, id)
}
