package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	graphql_model1 "pulse/graph/graphql_model"

	"github.com/google/uuid"
)

// CreateAlert is the resolver for the createAlert field.
func (r *mutationResolver) CreateAlert(ctx context.Context, input graphql_model1.CreateAlertInput) (*graphql_model1.Alert, error) {
	panic(fmt.Errorf("not implemented: CreateAlert - createAlert"))
}

// DeleteAlert is the resolver for the deleteAlert field.
func (r *mutationResolver) DeleteAlert(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAlert - deleteAlert"))
}

// Alerts is the resolver for the alerts field.
func (r *queryResolver) Alerts(ctx context.Context) ([]*graphql_model1.Alert, error) {
	panic(fmt.Errorf("not implemented: Alerts - alerts"))
}
