package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	graphql_model1 "pulse/graph/graphql_model"
	"time"
)

// PortfolioStats is the resolver for the portfolioStats field.
func (r *queryResolver) PortfolioStats(ctx context.Context) (*graphql_model1.PortfolioStats, error) {
	panic(fmt.Errorf("not implemented: PortfolioStats - portfolioStats"))
}

// PortfolioMetrics is the resolver for the portfolioMetrics field.
func (r *queryResolver) PortfolioMetrics(ctx context.Context, from time.Time, to time.Time) ([]*graphql_model1.PortfolioMetric, error) {
	panic(fmt.Errorf("not implemented: PortfolioMetrics - portfolioMetrics"))
}
