package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	graphql_model1 "pulse/graph/graphql_model"
)

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context) ([]*graphql_model1.Transaction, error) {
	panic(fmt.Errorf("not implemented: Transactions - transactions"))
}

// TransactionCategories is the resolver for the transactionCategories field.
func (r *queryResolver) TransactionCategories(ctx context.Context) ([]*graphql_model1.TransactionCategory, error) {
	panic(fmt.Errorf("not implemented: TransactionCategories - transactionCategories"))
}
