package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	graphql_model1 "pulse/graph/graphql_model"

	"github.com/google/uuid"
)

// CreateWallet is the resolver for the createWallet field.
func (r *mutationResolver) CreateWallet(ctx context.Context, input graphql_model1.CreateWalletInput) (*graphql_model1.Wallet, error) {
	panic(fmt.Errorf("not implemented: CreateWallet - createWallet"))
}

// CreateSubwallet is the resolver for the createSubwallet field.
func (r *mutationResolver) CreateSubwallet(ctx context.Context, input graphql_model1.CreateSubwalletInput) (*graphql_model1.Subwallet, error) {
	panic(fmt.Errorf("not implemented: CreateSubwallet - createSubwallet"))
}

// Wallets is the resolver for the wallets field.
func (r *queryResolver) Wallets(ctx context.Context) ([]*graphql_model1.Wallet, error) {
	panic(fmt.Errorf("not implemented: Wallets - wallets"))
}

// Wallet is the resolver for the wallet field.
func (r *queryResolver) Wallet(ctx context.Context, id uuid.UUID) (*graphql_model1.Wallet, error) {
	panic(fmt.Errorf("not implemented: Wallet - wallet"))
}

// Subwallet is the resolver for the subwallet field.
func (r *queryResolver) Subwallet(ctx context.Context, id uuid.UUID) (*graphql_model1.Subwallet, error) {
	panic(fmt.Errorf("not implemented: Subwallet - subwallet"))
}
