// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_model

import (
	"time"

	"github.com/google/uuid"
)

type AddressTableLookup struct {
	AccountKey      string  `json:"account_key"`
	ReadonlyIndexes []int32 `json:"readonly_indexes"`
	WritableIndexes []int32 `json:"writable_indexes"`
}

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type InnerInstruction struct {
	Index        int32          `json:"index"`
	Instructions []*Instruction `json:"instructions"`
}

type Instruction struct {
	Accounts       []int32 `json:"accounts"`
	Data           string  `json:"data"`
	ProgramIDIndex int32   `json:"program_id_index"`
	StackHeight    int32   `json:"stack_height"`
}

type Job struct {
	ID            string `json:"id"`
	WalletAddress string `json:"walletAddress"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MessageHeader struct {
	NumReadonlySignedAccounts   int32 `json:"num_readonly_signed_accounts"`
	NumReadonlyUnsignedAccounts int32 `json:"num_readonly_unsigned_accounts"`
	NumRequiredSignatures       int32 `json:"num_required_signatures"`
}

type Meta struct {
	ComputeUnitsConsumed int32               `json:"compute_units_consumed"`
	Fee                  int32               `json:"fee"`
	InnerInstructions    []*InnerInstruction `json:"inner_instructions"`
	LogMessages          []string            `json:"log_messages"`
	PostBalances         []int32             `json:"post_balances"`
	PreBalances          []int32             `json:"pre_balances"`
	PostTokenBalances    []*TokenBalance     `json:"post_token_balances"`
	PreTokenBalances     []*TokenBalance     `json:"pre_token_balances"`
	Rewards              []*Reward           `json:"rewards"`
	Status               *Status             `json:"status"`
}

type Mutation struct {
}

type PricePoint struct {
	Timestamp int32   `json:"Timestamp"`
	Open      float64 `json:"Open"`
	High      float64 `json:"High"`
	Low       float64 `json:"Low"`
	Close     float64 `json:"Close"`
	Volume    float64 `json:"Volume"`
}

type Query struct {
}

type RegisterInput struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type Reward struct {
	Info string `json:"info"`
}

type Status struct {
	Ok           *string `json:"ok,omitempty"`
	ErrorMessage *string `json:"error_message,omitempty"`
}

type StatusMessage struct {
	Status string `json:"status"`
}

type Subscription struct {
}

type Token struct {
	Name          string        `json:"name"`
	Address       string        `json:"address"`
	Pool          string        `json:"pool"`
	Description   string        `json:"description"`
	Image         string        `json:"image"`
	Amount        float64       `json:"amount"`
	Price         float64       `json:"price"`
	Pnl           float64       `json:"pnl"`
	Invested      float64       `json:"invested"`
	Value         float64       `json:"value"`
	HistoryPrices []*PricePoint `json:"history_prices"`
}

type TokenAmount struct {
	Amount         string  `json:"amount"`
	Decimals       int32   `json:"decimals"`
	UIAmount       float64 `json:"ui_amount"`
	UIAmountString string  `json:"ui_amount_string"`
}

type TokenBalance struct {
	AccountIndex  int32        `json:"account_index"`
	Mint          string       `json:"mint"`
	Owner         string       `json:"owner"`
	ProgramID     string       `json:"program_id"`
	UITokenAmount *TokenAmount `json:"ui_token_amount"`
}

type Transaction struct {
	Jsonrpc string             `json:"jsonrpc"`
	Result  *TransactionResult `json:"result,omitempty"`
	Err     *Error             `json:"err,omitempty"`
	ID      int32              `json:"id"`
}

type TransactionData struct {
	Message    *TransactionMessage `json:"message"`
	Signatures []string            `json:"signatures"`
}

type TransactionMessage struct {
	AccountKeys         []string              `json:"account_keys"`
	AddressTableLookups []*AddressTableLookup `json:"address_table_lookups"`
	Header              *MessageHeader        `json:"header"`
	Instructions        []*Instruction        `json:"instructions"`
	RecentBlockhash     string                `json:"recent_blockhash"`
}

type TransactionResult struct {
	BlockTime   int32            `json:"block_time"`
	Meta        *Meta            `json:"meta"`
	Slot        int32            `json:"slot"`
	Transaction *TransactionData `json:"transaction"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
}

type Wallet struct {
	Address      string         `json:"address"`
	SolBalance   float64        `json:"sol_balance"`
	SolValue     float64        `json:"sol_value"`
	WalletValue  float64        `json:"wallet_value"`
	Tokens       []*Token       `json:"tokens"`
	Transactions []*Transaction `json:"transactions"`
	LastUpdated  string         `json:"last_updated"`
}

type WalletUpdate struct {
	JobID    string  `json:"JobID"`
	Progress int32   `json:"Progress"`
	Wallet   *Wallet `json:"Wallet"`
}
