// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_model

import (
	"time"

	"github.com/google/uuid"
)

type Alert struct {
	ID                   uuid.UUID `json:"id"`
	CreatedAt            time.Time `json:"createdAt"`
	UpdatedAt            time.Time `json:"updatedAt"`
	User                 *User     `json:"user"`
	Token                *Token    `json:"token"`
	Condition            string    `json:"condition"`
	NotificationSettings *string   `json:"notificationSettings,omitempty"`
}

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Chain struct {
	ID         uuid.UUID    `json:"id"`
	CreatedAt  time.Time    `json:"createdAt"`
	UpdatedAt  time.Time    `json:"updatedAt"`
	Name       string       `json:"name"`
	Subwallets []*Subwallet `json:"subwallets"`
}

type CreateAlertInput struct {
	TokenID              uuid.UUID `json:"tokenId"`
	Condition            string    `json:"condition"`
	NotificationSettings *string   `json:"notificationSettings,omitempty"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type HistoricalPrice struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	Token     *Token    `json:"token"`
	Date      time.Time `json:"date"`
	Price     string    `json:"price"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PortfolioMetric struct {
	ID           uuid.UUID `json:"id"`
	CreatedAt    time.Time `json:"createdAt"`
	User         *User     `json:"user"`
	MetricName   string    `json:"metricName"`
	MetricValue  string    `json:"metricValue"`
	CalculatedAt time.Time `json:"calculatedAt"`
}

type PortfolioStats struct {
	TotalValue      string            `json:"totalValue"`
	TotalPnl        string            `json:"totalPnl"`
	DailyChange     string            `json:"dailyChange"`
	TopPerformers   []*SubwalletToken `json:"topPerformers"`
	WorstPerformers []*SubwalletToken `json:"worstPerformers"`
}

type Query struct {
}

type RegisterInput struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type Role struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Name      string    `json:"name"`
	Users     []*User   `json:"users"`
}

type Snapshot struct {
	ID           uuid.UUID  `json:"id"`
	CreatedAt    time.Time  `json:"createdAt"`
	Subwallet    *Subwallet `json:"subwallet"`
	SnapshotDate time.Time  `json:"snapshotDate"`
	TotalPnl     string     `json:"totalPnl"`
	TotalValue   string     `json:"totalValue"`
}

type Subwallet struct {
	ID        uuid.UUID         `json:"id"`
	CreatedAt time.Time         `json:"createdAt"`
	UpdatedAt time.Time         `json:"updatedAt"`
	Name      string            `json:"name"`
	Chain     *Chain            `json:"chain"`
	Tokens    []*SubwalletToken `json:"tokens"`
	Snapshots []*Snapshot       `json:"snapshots"`
	Address   string            `json:"address"`
}

type SubwalletToken struct {
	ID        uuid.UUID        `json:"id"`
	CreatedAt time.Time        `json:"createdAt"`
	UpdatedAt time.Time        `json:"updatedAt"`
	Token     *Token           `json:"token"`
	Amount    string           `json:"amount"`
	ValueUsd  string           `json:"valueUsd"`
	TotalPnl  string           `json:"totalPnl"`
	Snapshot  []*TokenSnapshot `json:"snapshot"`
}

type Token struct {
	ID               uuid.UUID          `json:"id"`
	CreatedAt        time.Time          `json:"createdAt"`
	UpdatedAt        time.Time          `json:"updatedAt"`
	Name             string             `json:"name"`
	CurrentUsdValue  string             `json:"currentUsdValue"`
	LastUpdated      time.Time          `json:"lastUpdated"`
	HistoricalPrices []*HistoricalPrice `json:"historicalPrices"`
}

type TokenSnapshot struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	ValueUsd  string    `json:"valueUsd"`
}

type Transaction struct {
	ID                    uuid.UUID            `json:"id"`
	CreatedAt             time.Time            `json:"createdAt"`
	UpdatedAt             time.Time            `json:"updatedAt"`
	Token                 *Token               `json:"token"`
	TransactionType       string               `json:"transactionType"`
	Amount                string               `json:"amount"`
	ValueUsdAtTransaction string               `json:"valueUsdAtTransaction"`
	TransactionDate       time.Time            `json:"transactionDate"`
	Category              *TransactionCategory `json:"category"`
}

type TransactionCategory struct {
	ID           uuid.UUID      `json:"id"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
	Name         string         `json:"name"`
	Transactions []*Transaction `json:"transactions"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt time.Time          `json:"createdAt"`
	UpdatedAt time.Time          `json:"updatedAt"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Wallets   []*Wallet          `json:"wallets"`
	Alerts    []*Alert           `json:"alerts"`
	Roles     []*Role            `json:"roles"`
	Metrics   []*PortfolioMetric `json:"metrics"`
}

type Wallet struct {
	ID         uuid.UUID    `json:"id"`
	CreatedAt  time.Time    `json:"createdAt"`
	UpdatedAt  time.Time    `json:"updatedAt"`
	Name       string       `json:"name"`
	Subwallets []*Subwallet `json:"subwallets"`
}

type CreateSubwalletInput struct {
	Name     string    `json:"name"`
	WalletID uuid.UUID `json:"walletId"`
	ChainID  uuid.UUID `json:"chainId"`
	Address  string    `json:"address"`
}

type CreateWalletInput struct {
	Name string `json:"name"`
}
