/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChainsImport } from './routes/_authenticated/chains'
import { Route as AuthenticatedWalletsIndexImport } from './routes/_authenticated/wallets/index'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedWalletsSubwalletsImport } from './routes/_authenticated/wallets/subwallets'
import { Route as AuthenticatedWalletsPerformanceImport } from './routes/_authenticated/wallets/performance'
import { Route as AuthenticatedSettingsGeneralImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedWalletsWalletWalletIdImport } from './routes/_authenticated/wallets/wallet/$walletId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedChainsRoute = AuthenticatedChainsImport.update({
  id: '/chains',
  path: '/chains',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedWalletsIndexRoute = AuthenticatedWalletsIndexImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedWalletsSubwalletsRoute =
  AuthenticatedWalletsSubwalletsImport.update({
    id: '/wallets/subwallets',
    path: '/wallets/subwallets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedWalletsPerformanceRoute =
  AuthenticatedWalletsPerformanceImport.update({
    id: '/wallets/performance',
    path: '/wallets/performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedWalletsWalletWalletIdRoute =
  AuthenticatedWalletsWalletWalletIdImport.update({
    id: '/wallets/wallet/$walletId',
    path: '/wallets/wallet/$walletId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/chains': {
      id: '/_authenticated/chains'
      path: '/chains'
      fullPath: '/chains'
      preLoaderRoute: typeof AuthenticatedChainsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/wallets/performance': {
      id: '/_authenticated/wallets/performance'
      path: '/wallets/performance'
      fullPath: '/wallets/performance'
      preLoaderRoute: typeof AuthenticatedWalletsPerformanceImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/wallets/subwallets': {
      id: '/_authenticated/wallets/subwallets'
      path: '/wallets/subwallets'
      fullPath: '/wallets/subwallets'
      preLoaderRoute: typeof AuthenticatedWalletsSubwalletsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/wallets/': {
      id: '/_authenticated/wallets/'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/wallets/wallet/$walletId': {
      id: '/_authenticated/wallets/wallet/$walletId'
      path: '/wallets/wallet/$walletId'
      fullPath: '/wallets/wallet/$walletId'
      preLoaderRoute: typeof AuthenticatedWalletsWalletWalletIdImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedChainsRoute: typeof AuthenticatedChainsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedWalletsPerformanceRoute: typeof AuthenticatedWalletsPerformanceRoute
  AuthenticatedWalletsSubwalletsRoute: typeof AuthenticatedWalletsSubwalletsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedWalletsIndexRoute: typeof AuthenticatedWalletsIndexRoute
  AuthenticatedWalletsWalletWalletIdRoute: typeof AuthenticatedWalletsWalletWalletIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChainsRoute: AuthenticatedChainsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedWalletsPerformanceRoute: AuthenticatedWalletsPerformanceRoute,
  AuthenticatedWalletsSubwalletsRoute: AuthenticatedWalletsSubwalletsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedWalletsIndexRoute: AuthenticatedWalletsIndexRoute,
  AuthenticatedWalletsWalletWalletIdRoute:
    AuthenticatedWalletsWalletWalletIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/chains': typeof AuthenticatedChainsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/wallets/performance': typeof AuthenticatedWalletsPerformanceRoute
  '/wallets/subwallets': typeof AuthenticatedWalletsSubwalletsRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/wallets': typeof AuthenticatedWalletsIndexRoute
  '/wallets/wallet/$walletId': typeof AuthenticatedWalletsWalletWalletIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/chains': typeof AuthenticatedChainsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/wallets/performance': typeof AuthenticatedWalletsPerformanceRoute
  '/wallets/subwallets': typeof AuthenticatedWalletsSubwalletsRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/wallets': typeof AuthenticatedWalletsIndexRoute
  '/wallets/wallet/$walletId': typeof AuthenticatedWalletsWalletWalletIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/chains': typeof AuthenticatedChainsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/wallets/performance': typeof AuthenticatedWalletsPerformanceRoute
  '/_authenticated/wallets/subwallets': typeof AuthenticatedWalletsSubwalletsRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/wallets/': typeof AuthenticatedWalletsIndexRoute
  '/_authenticated/wallets/wallet/$walletId': typeof AuthenticatedWalletsWalletWalletIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/chains'
    | '/dashboard'
    | '/settings/general'
    | '/wallets/performance'
    | '/wallets/subwallets'
    | '/settings'
    | '/wallets'
    | '/wallets/wallet/$walletId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/chains'
    | '/dashboard'
    | '/settings/general'
    | '/wallets/performance'
    | '/wallets/subwallets'
    | '/settings'
    | '/wallets'
    | '/wallets/wallet/$walletId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/chains'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings/general'
    | '/_authenticated/wallets/performance'
    | '/_authenticated/wallets/subwallets'
    | '/_authenticated/settings/'
    | '/_authenticated/wallets/'
    | '/_authenticated/wallets/wallet/$walletId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/chains",
        "/_authenticated/dashboard",
        "/_authenticated/settings/general",
        "/_authenticated/wallets/performance",
        "/_authenticated/wallets/subwallets",
        "/_authenticated/settings/",
        "/_authenticated/wallets/",
        "/_authenticated/wallets/wallet/$walletId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/chains": {
      "filePath": "_authenticated/chains.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/general": {
      "filePath": "_authenticated/settings/general.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/wallets/performance": {
      "filePath": "_authenticated/wallets/performance.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/wallets/subwallets": {
      "filePath": "_authenticated/wallets/subwallets.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/wallets/": {
      "filePath": "_authenticated/wallets/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/wallets/wallet/$walletId": {
      "filePath": "_authenticated/wallets/wallet/$walletId.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
